use_gazebo: false
command_in_type: "speed_units"
scale:
  linear:  0.4
  rotational: 0.8
  joint: 0.5 
command_out_type: "trajectory_msgs/JointTrajectory"
command_out_topic: /scaled_joint_trajectory_controller/joint_trajectory
publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false
move_group_name:  ur_manipulator 
planning_frame: base_link       
ee_frame_name: tool0  
robot_link_command_frame: base_link  
incoming_command_timeout:  0.1  
num_outgoing_halt_msgs_to_publish: 4
lower_singularity_threshold:  17.0  
hard_stop_singularity_threshold: 30.0 
joint_limit_margin: 0.1 
leaving_singularity_threshold_multiplier: 2.0 
cartesian_command_in_topic: /servo_node/delta_twist_cmds  
joint_command_in_topic: /servo_node/delta_joint_cmds      
check_collisions: false 
collision_check_rate: 10.0 
self_collision_proximity_threshold: 0.01 
scene_collision_proximity_threshold: 0.02 
collision_distance_safety_factor: 1000.0 
min_allowable_collision_distance: 0.01
status_topic: ~/status 
